audio:
  n_fft: 1200
  num_freq: 601 # n_fft//2 + 1
  sample_rate: 8000
  hop_length: 160
  win_length: 400
  min_level_db: -100.0
  ref_level_db: 20.0
  preemphasis: 0.97
  power: 0.30
---
model:
  lstm_dim: 400
  fc1_dim: 600
  fc2_dim: 601 # num_freq
---
data:
  train_dir: ''
  test_dir: ''
  audio_len: 3.0
---
form:
  input: '/star-home/jinzengrui/data/LibriheavyCSS/train_small_2spk_kaldi_fmt/mix.scp'
  mix2spk: '/star-home/jinzengrui/data/LibriheavyCSS/train_small_2spk_kaldi_fmt/mix2spk'
  spk2src: '/star-home/jinzengrui/data/LibriheavyCSS/train_small_2spk_kaldi_fmt/spk2src'
  spk2spk: '/star-home/jinzengrui/data/LibriheavyCSS/train_small_2spk_kaldi_fmt/spk2spk'
---
dev:
  input: '/star-home/jinzengrui/data/LibriheavyCSS/dev_2spk_kaldi_fmt/mix.scp'
  enrollments: '/star-home/jinzengrui/data/LibriheavyCSS/dev_2spk_kaldi_fmt/enrollments'
  mix2spk: '/star-home/jinzengrui/data/LibriheavyCSS/dev_2spk_kaldi_fmt/mix2spk'
  spk2src: '/star-home/jinzengrui/data/LibriheavyCSS/dev_2spk_kaldi_fmt/spk2src'
  spk2spk: '/star-home/jinzengrui/data/LibriheavyCSS/dev_2spk_kaldi_fmt/spk2spk'
---
train:
  batch_size: 36
  num_workers: 16
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  summary_interval: 1
  checkpoint_interval: 1000
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
---
embedder: # d-vector embedder. don't fix it!
  num_mels: 40
  n_fft: 512
  emb_dim: 256
  lstm_hidden: 768
  lstm_layers: 3
  window: 80
  stride: 40
